version: "2"

services:
  wordpress:
    image: "chriszarate/wordpress:4.8.2"
    environment:
      WORDPRESS_ACTIVATE_PLUGINS: "options-definitely post-types-definitely gloggi-plugin" # plugin folder relative to /wp-content/plugins/
      WORDPRESS_ACTIVATE_THEME: "gloggi-theme"   # theme folder relative to /wp-content/themes/
      WORDPRESS_DB_PASSWORD: "xBkLnzRvNWB6Zd56"
      WORDPRESS_SITE_TITLE: "WORDPRESS_SITE_TITLE"
      WORDPRESS_SITE_USER: "al"
      WORDPRESS_SITE_PASSWORD: "gloggi"
    env_file:
        - ./.env
        - ./.env.local
    depends_on:
      - "mysql"
    volumes:
      - "./gloggi-plugin:/var/www/html/wp-content/plugins/gloggi-plugin"
      - "./gloggi-theme:/var/www/html/wp-content/themes/gloggi-theme"
      - "./post-install.sh:/usr/bin/post-install.sh"
    ports:
      - 80:80
    command: bash -c "runuser www-data -s /bin/sh -c 'post-install.sh wp' && apache2-foreground"
  mysql:
    image: "mariadb:10.2"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_DATABASE: "wordpress"
      MYSQL_ROOT_PASSWORD: "xBkLnzRvNWB6Zd56"
